[project]
name = "xarp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "caetanolab", email = "152355265+caetanolab@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "msgpack>=1.1.2",
    "numpy>=2.4.0",
    "pillow>=12.1.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "qrcode[pil]>=8.2",
    "streamlit>=1.52.2",
    "uvicorn>=0.40.0",
    "websockets>=15.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ty>=0.0.8",
]

[project.scripts]
web = "xarp.web:run"
